[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:Warning
    ignore:.*StarletteDeprecationWarning.*
    ignore::UserWarning
